sudo: false
language: node_js
node_js:
- lts/*
- node
script:
- npm run ci
notifications:
  slack:
    secure: afJTcfHzd1xFlvGvhV4e6sJEoeYeZXJRu9yyu8SswRafGVY+wU0TKH/88SVWOdXcwiNoi84yAAhQxZhFmNkbvz4BTtgZQXuEaz9LEP3Suovjk6NQPifPQWxg0htjjXDQAV64rIujUoxgZIjtlD4F6WADFC4Nw0Sdcv9Pz9JbIBWkjnT0iUzxnjmVorQ29jVJjEZTZMC5UNWzky8Xc9wx6Pc4LtVVqW+27qzOS+3xM7vvvG4lCGURHpAnCcjfFzkRxavOAa+qLcTM/aO0w0Vk1V3CYsWcUUHCQPMOhErjYjrstXUiUGsL2R1mDg6WKLTXLvf9RiA8pItCErsYvHRUbIqOWCPc4wl5QE1YkeS2qxdyFEOzaH71f39ML2lzyKP/pN0Joh7O4sPS7V/t1T7U9lxOvj5dmUyhdqelHejkE7j0tsxT+DV8o7JnfbAfV7Mf57OpTNVqGfwf4bL92VUdvvJ0S39BftEaNnYYYJkFU2RWKpZLfYxKFEKwVwIjkTb3aQX9EpNiGfaNhYnvW51Ll1+kIhuNCT2g4B2vdjTmIpo5qHltboCuhbE5AV+Jwg+Lw9TZyxyihlAh3cfZymcNRUDomPOnf/SjDuHEvOnidgol24f5J3yj7cqcgdg6auHMR+L1jUVdp5aj/R1lLQm2nXxKX9PwXs2aik/kXMnNSag=
